config/routes.rb
Fullow::Application.routes.draw do
  root 'players#index'

  get '/about' => 'players#about'
  get '/browse' => 'players#browse'
  get '/top10' => 'players#top10'
  get '/discuss' => 'players#discuss'
  get '/*slug' => 'players#show', as: 'player'
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_one :social_link
  has_many :game_stat
  has_one :career_stat
  has_one :season_stat

  def fullname
    "#{self.firstname} #{self.lastname}"
  end

  def slugify
    "#{self.firstname} #{self.lastname}".downcase.gsub(" ", "-").gsub("'", "")
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show]
  before_action :list_players

  def index
  end

  def show
    @scraper = GetGameStats.new(@player)
    @list = GetYoutube.new.get_youtube(@player.fullname)
    @player.views += 1
    @player.save
  end

  def top10
    sorted_players = @players.sort_by do |player| 
      player.views
    end
    @top_10 = sorted_players[-10..-1]
  end

  def discuss
  end

  def about
  end

  def browse
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find_by(slug: params[:slug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:firstname, :lastname)
    end

    def list_players
      @players = Player.all
      @players_array = @players.map do |p|
        { label: p.fullname, value: player_path(p.slug) }
      end
    end
end

app/helpers/players_helper.rb
module PlayersHelper
  def last_game_date
    @scraper.most_recent_0[:date]
  end

  def last_game_result
    "#{@scraper.most_recent_0[:score]} #{@scraper.most_recent_0[:vs]}"
  end

  def top_three_stats
    hash = {
      :reb        => @scraper.most_recent_0[:reb].to_i,
      :ast        => @scraper.most_recent_0[:ast].to_i,
      :blk        => @scraper.most_recent_0[:blk].to_i,
      :stl        => @scraper.most_recent_0[:stl].to_i,
      :turnovers  => @scraper.most_recent_0[:turnovers].to_i,
      :pts        => @scraper.most_recent_0[:pts].to_i
    }
    hash.sort_by { |k,v| v }.reverse[0..2].map do |stat_array|
      long_ass_string = <<-eos
        <li><strong>#{stat_array[1]}</strong><br>
        #{stat_array[0]}
        </li>
      eos
    end.join
  end

  def season_averages_table
    long_ass_string = <<-eos
    <table class="fullow-table">
      <tr>#{table_header(@scraper.season_averages_hash)}</tr>
      <tr>#{table_row(@scraper.season_averages_hash)}</tr>
    </table>
    eos
  end

  def table_header(hash)
    hash.map do |k, v|
      case k
      when :threepointp
        "<th title=\"3-Point Field Goal Percentage\">3p%</th>"
      when :turnovers
        "<th title=\"Turnovers Per Game\">topg</th>"
      else
        "<th>#{k}</th>"
      end
    end.join
  end

  def table_row(hash)
    hash.map do |k, v|
      "<td>#{v}</td>"
    end.join
  end

  def career_averages_table
    long_ass_string = <<-eos
      <table class="fullow-table">
      <tr>#{table_header(@scraper.career_averages_hash)}</tr>
      <tr>#{table_row(@scraper.career_averages_hash)}</tr>
      </table>
    eos
  end
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/about.html.erb
<div id="fullow-about">
  <div class="jumbotron center about-custom">
    <p><strong>NBAStalk</strong> is a social media and statistics aggregator. Nowadays your favorite athlete has too many social media sites. NBAStalk collects the latest information on your favorite player and presents it to you in one easy to follow dashboard.</p>

    <p>Built by
        <a href="https://twitter.com/jamesjtong" target="_blank">@jamesjtong</a>,
        <a href="https://twitter.com/samtalks" target="_blank">@samtalks</a>,
        <a href="https://twitter.com/theevo" target="_blank">@theevo </a>
    </p>
  </div>

</div>

app/views/players/browse.html.erb
<div class="list-group">
  <a href="#" class="list-group-item active">
    List of Players
  </a>
  <% @players_array.each do |player| %>
    <a href=<%= player[:value] %> class="list-group-item"><%= player[:label] %></a>
  <% end %>
    
</div>

app/views/players/discuss.html.erb
<div id="fullow-discuss" >
  <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1395871487324611";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

  <div class="fb-comments glob-discuss" data-href="nbastalk.com/discuss" data-numposts="5" data-colorscheme="light"
  css="/application.css" width="880px">
<!-- cannot overwrite facebook custom iframe width of 100%-->
  </div>
</div>

app/views/players/index.html.erb
<script type="text/javascript">
  $(function() {
    // index's autocomplete search
    var availablePlayers = <%= raw @players_array.to_json %>;
    $( "#players" ).autocomplete({
      source: availablePlayers,
      select: function( event, ui ) {
        window.location.href = ui.item.value;
        event.preventDefault();
      },
      focus: function(event,ui){
        var name = ui.item.label;
        $('.ui-autocomplete-input').val(name);
        event.preventDefault();
      }
    });
    $(document).keypress(function(e) {
      if(e.which == 13) {
        var player_choice = $( "#players" ).val();
        var player_hash = $.grep(availablePlayers, function(hash){
          return hash.label.toLowerCase() == player_choice.toLowerCase();
        });
        var value = player_hash[0].value;
        window.location.href = value;
      }
    });
  });

</script>
<div id="fullow-wallpaper">
  <h2 style="margin-left:1em"><font color="white">
    <br><br><br><br>NBAStalk </font></style>
      <input id="players" placeholder="Carmelo Anthony" />
  </h2>
  <div style="height:67%">
  </div>
</div>

app/views/players/show.html.erb
<div class="container">
  <div id="fb-root"></div>

  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-6">
      <div class="jumbotron">
        <h1><%= @player.firstname %> <%= @player.lastname %></h1>
        <img src="<%= @scraper.picture %>">
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <span class="panel-title">Next Game:&nbsp;&nbsp;&nbsp;</span>
          <span><%= @scraper.game_matchup %></span>
          <span class="pull-right"><%= @scraper.game_time %> <%= @scraper.game_day %></span>
        </div>
      </div>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <span class="panel-title">Last Game</span>
          <span class="pull-right"><%= last_game_date %></span>
        </div>
        <div class="panel-body">
          <%= last_game_result %><br>
          <ul class="fullow-stats">
          <%= raw top_three_stats %>
          </ul>
        </div>
      </div>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <span class="panel-title">Season Averages</span>
          <span class="pull-right">2013-14</span>
        </div>
        <div class="panel-body">
          <%= raw season_averages_table %>
        </div>
      </div>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <span class="panel-title">Career Averages</span>
        </div>
        <div class="panel-body">
          <%= raw career_averages_table %>
        </div>
      </div>
    </div>
</div>

<div class="row" style="margin-top:2em;">
  <% begin %>
    <div class="col-sm-6">
      <a class="twitter-timeline" href="https://twitter.com/jlin7" data-widget-id="402571380798922752" data-screen-name="<%= @player.social_link.twitter.gsub("https://twitter.com/","") %>"></a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
  <% rescue %>
  <% end %>
  <div class="col-sm-6">
    <% @list.each do |part| %>
      <iframe width="456" height="300" src="//www.youtube.com/embed/<%= part %>" frameborder="0" allowfullscreen></iframe><br>
    <% end %>
  </div>
</div>

<div class="row" style="margin-top:2em;">
  <div class="col-sm-6">
    <div class="fb-comments" data-href="<%= player_url %>" data-width="456" data-numposts="5" data-colorscheme="dark">
    </div>
  </div>

  <% begin %>
  <div class="col-sm-6">
    <div class="fb-like-box" data-href="<%= @player.social_link.facebook %>" data-width="456" data-colorscheme="dark" data-show-faces="false" data-header="false" data-stream="true" data-show-border="true"></div>
  </div>
  <% rescue %>
  <% end %>
</div>

app/views/players/top10.html.erb
<ul class="list-group">
  <% 10.times do |rank| %>
    <li class="list-group-item james-list">
    <span class="badge pull-left"><%= rank+1 %></span>
    <a href="/<%=@top_10[-(rank)-1].slug %>"><%= @top_10[-(rank)-1].fullname %></a>
    </li>
  <% end %>
</ul>